In [41]:
from bs4 import BeautifulSoup
import sys
import pandas as pd

In [40]:
from selenium import webdriver
import time
try:
    driver = webdriver.PhantomJS(executable_path='/usr/local//Cellar/phantomjs/2.1.1/bin/phantomjs')
    driver.get('https://www.morningstar.com/stocks/xshe/000423/quote.html')
    time.sleep(10)
    soup = BeautifulSoup(driver.page_source, 'html.parser')
    driver.close()
except:
    print('Do not use VPN !!!')
    print('Do not use VPN !!!')
    print('Do not use VPN !!!')
    print('Err:', sys.exc_info()[0])

/anaconda2/envs/python3env/lib/python3.6/site-packages/selenium/webdriver/phantomjs/webdriver.py:49: UserWarning: Selenium support for PhantomJS has been deprecated, please use headless versions of Chrome or Firefox instead
  warnings.warn('Selenium support for PhantomJS has been deprecated, please use headless '

In [39]:
soupTable = soup.find('table', {'class' : 'report-table ng-isolate-scope'})

In [44]:
trList = soupTable.findAll('tr')

data = {}
for tr in trList:
    tds = tr.findAll('td')
    column = [td.getText().strip() for td in tds]
    data[column[0]] = column[1:]

df = pd.DataFrame(data)
df.set_index('Fiscal', inplace=True)
df

,Average Shares Outstanding (Mil),Capital Spending (Mil),Diluted Earnings Per Share,Free Cash Flow (Bil),Net Income (Bil),Operating Cash Flow (Bil),Operating Income (Bil),Operating Margin %,Revenue (Bil)
Fiscal,,,,,,,,,
2008,,,,,,,,,
2009,,,,,,,,,
2010,,,,,,,,,
2011,,,,,,,,,
2012,,,,,,,,,
2013,—,-481.08,1.84,0.40,1.20,0.88,1.33,33.12,4.02
2014,654.03,-275.70,2.09,0.38,1.37,0.66,1.46,36.32,4.01
2015,654.01,-284.25,2.48,0.69,1.63,0.98,1.76,32.23,5.45
2016,654.03,-350.60,2.83,0.27,1.85,0.62,2.05,32.44,6.32
2017,654.03,-313.94,3.13,1.44,2.04,1.76,2.32,31.47,7.37
YTD,654.02,-50.85,0.93,-0.44,0.61,1.76,0.70,41.36,1.70
TTM,654.03,-276.58,3.13,0.95,2.05,1.76,2.33,31.50,7.39
5-Yr Avg,654.02,-343.20,2.41,0.49,1.58,—,1.73,33.13,5.26
5-Yr Growth,0.00,2.26,0.14,20.12,14.47,15.42,16.08,-2.67,19.26